CONFIG_ZMK_MOUSE=y

CONFIG_ZMK_MOUSE_DEFAULT_MOVE_VAL=1000
CONFIG_ZMK_MOUSE_DEFAULT_SCROLL_VAL=20

#CONFIG_ZMK_POINTING=y
# マウス移動速度(default=600)
#CONFIG_ZMK_POINTING_DEFAULT_MOVE_VAL=6000
# スクロール量(default=10)
#CONFIG_ZMK_POINTING_DEFAULT_SCRL_VAL=100